version: "3.9"
services:
  # Web App server
  web:
    build: .
    links:
      - mongo
      - mysql
    ports:
      - "8080:8080"
  # Rabbitmq server
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  # Mysql DB server
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'toor'
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    volumes:
      - mysql_vol:/var/lib/mysql
    expose:
      - '3306'
  # Mongo DB server
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=toor
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/var/lib/mongo
# DB volumes
volumes:
    mysql_vol:
    mongo_vol: